"""create roadmap tables

Revision ID: bcaa85cc541e
Revises: 
Create Date: 2026-07-09 15:22:35.836651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcaa85cc541e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_title', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=50), nullable=False),
    sa.Column('known_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_style', sa.String(length=50), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmaps'))
    )
    op.create_index(op.f('ix_roadmaps_goal_title'), 'roadmaps', ['goal_title'], unique=False)
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_tasks_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_tasks'))
    )
    op.create_index(op.f('ix_roadmap_tasks_roadmap_id'), 'roadmap_tasks', ['roadmap_id'], unique=False)
    op.create_table('roadmap_subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap_tasks.id'], name=op.f('fk_roadmap_subtasks_task_id_roadmap_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_subtasks'))
    )
    op.create_index(op.f('ix_roadmap_subtasks_task_id'), 'roadmap_subtasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_subtasks_task_id'), table_name='roadmap_subtasks')
    op.drop_table('roadmap_subtasks')
    op.drop_index(op.f('ix_roadmap_tasks_roadmap_id'), table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_index(op.f('ix_roadmaps_goal_title'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
